<a href="https://colab.research.google.com/github/Crocodyll1/Machine-Learning/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy - Numerical Python
Advantages of Numpy Arrays:
  1.Allows several Mathematical     
  operations
  2.Faster opertions
  

In [116]:
import numpy as np

List vs Nimpy - Time taken

In [117]:
from time import process_time


Time taken by a list

In [118]:
python_list =[i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.001188251000002083


In [119]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5

end_time = process_time()

print(end_time - start_time)

0.0010611959999984322


In [120]:
#list
list = [1,2,3,4,5]
print(list)
type(list)

[1, 2, 3, 4, 5]


list

In [121]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)   #ndarray represents n-dimensional array

[1 2 3 4 5]


numpy.ndarray

In [122]:
#creatong a 1 dim array
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [123]:
a.shape   # .shape tells the rows and columns of a matrix


(5,)

In [124]:
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [125]:
b.shape

(2, 4)

In [126]:
c= np.array([(1,2,3,4),(5,6,7,8)],dtype = float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial placeholders in numpy array

In [127]:
# create a numpy of Zeros

x = np.zeros((4,5))
print(x)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [128]:
 # create a numpy array of ones

y = np.ones((3,4))
print(y)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [129]:
# create a numpy array of a partcular value

z = np.full((4,5),5)
print(z)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [130]:
# create an identity matrix
#identity matrix has always rows = columns
a =  np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [131]:
# create a numpy array with random values

b = np.random.random((3,4))
print(b)

[[0.26264915 0.01074566 0.35547058 0.52179902]
 [0.64600719 0.20028082 0.51396549 0.50590393]
 [0.39831597 0.52923464 0.69843693 0.65714549]]


In [132]:
# random integer values array within a specific range

c = np.random.randint(10,100,(3,5))
print(c)

[[30 95 70 10 73]
 [78 53 42 84 43]
 [85 33 19 60 99]]


In [133]:
# array of evenly spaced values  --> specifying the number of values required

d =  np.linspace(10,30,6)
print(d)

[10. 14. 18. 22. 26. 30.]


In [134]:
#array of evenly spaced values  --> specifying the step

e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [135]:
a = np.random.randint(0, 10, (3,3))
b = np.random.randint(10, 20, (3,3))

print(a)
print(b)

[[2 8 6]
 [7 9 9]
 [2 2 6]]
[[11 16 17]
 [19 18 12]
 [12 14 19]]


Analysing a numpy array

In [136]:
c = np.random.randint(10,90,(5,5))
print(c)

print(c.shape)


[[64 21 48 20 78]
 [58 31 10 13 11]
 [39 39 44 83 40]
 [25 40 49 14 52]
 [55 46 21 78 79]]
(5, 5)


In [137]:
#number of dimesions

print(c.ndim)

2


In [138]:
# number of elements in an array

print(c.size)

25


In [139]:
#checking the data type of the values in the array
print(c.dtype)

int64


Mathematical oprerations on a np array

In [140]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2) # concatenate or joins two list



[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [141]:
k =  np.random.randint(0,10,(3,3))
l =  np.random.randint(10,20,(3,3))

print(k)
print(l)



[[9 6 7]
 [7 4 2]
 [1 9 8]]
[[16 14 13]
 [16 13 12]
 [13 16 13]]


In [143]:
print(k + l)
print(k - l)
print(k * l)
print(k / l)
#

[[25 20 20]
 [23 17 14]
 [14 25 21]]
[[ -7  -8  -6]
 [ -9  -9 -10]
 [-12  -7  -5]]
[[144  84  91]
 [112  52  24]
 [ 13 144 104]]
[[0.5625     0.42857143 0.53846154]
 [0.4375     0.30769231 0.16666667]
 [0.07692308 0.5625     0.61538462]]


In [ ]:
k =  np.random.randint(0,10(3,3))
l =  np.random.randint(10,20(3,3))

print(k)
print(l)


In [145]:
print(np.add(k,l))
print(np.subtract(k,l))
print(np.multiply(k,l))
print(np.divide(k,l))
#

[[25 20 20]
 [23 17 14]
 [14 25 21]]
[[ -7  -8  -6]
 [ -9  -9 -10]
 [-12  -7  -5]]
[[144  84  91]
 [112  52  24]
 [ 13 144 104]]
[[0.5625     0.42857143 0.53846154]
 [0.4375     0.30769231 0.16666667]
 [0.07692308 0.5625     0.61538462]]


Array Manipulation

In [147]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[0 4 5]
 [1 9 1]]
(2, 3)


In [148]:
# transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)


[[0 1]
 [4 9]
 [5 1]]
(3, 2)


In [151]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[0 1]
 [4 9]
 [5 1]]
(3, 2)


In [153]:
# Reshaping a array
a = np.random.randint(0,20,(2,3))

print(a)
print(a.shape)

b = a.reshape(3,2)
print(b)
print(b.shape)

[[ 3  3 17]
 [14  1 18]]
(2, 3)
[[ 3  3]
 [17 14]
 [ 1 18]]
(3, 2)
